name: Build & Release to Maven Central

on:
  push:
    branches:
      - develop
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: -Xmx4800m

    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        env:
          VERSION_NAME: ${{ env.version_name }}
        run: ./gradlew assemble

      - name: Lint Release
        run: ./gradlew lintRelease

      - name: Extract Branch Name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      # Check if the branch name matches the pattern "tags/v*.*.*" using regex
      - name: Deploy To Maven Central
        run: |
          echo ${{ secrets.MAVEN_CENTRAL_SEC_RING }} | base64 -d > $HOME/secring.gpg
          gpg --import --batch $HOME/secring.gpg
          ./gradlew clean publish \
          -PmavenCentralUsername="${{ secrets.SONATYPE_USERNAME }}" \
          -PmavenCentralPassword="${{ secrets.SONATYPE_PASSWORD }}" \
          -Psigning.keyId="${{ secrets.MAVEN_CENTRAL_KEY_ID }}" \
          -Psigning.password="${{ secrets.MAVEN_CENTRAL_KEY_PASSPHRASE }}" \
          -Psigning.secretKeyRingFile=$HOME/secring.gpg \
          -Porg.gradle.parallel=false \
          -Porg.gradle.daemon=false \
          --no-daemon
        if: success() && steps.extract_branch.outputs.branch == 'tags/v*.*.*'

      - name: Create Github Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
        if: success() && steps.extract_branch.outputs.branch == 'tags/v*.*.*'

